run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
